// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: user_service.proto

package user

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserStatus - статус пользователя
// Используем camelCase для совместимости с JSON
type UserStatus int32

const (
	// Неизвестный статус (default)
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	// Активный пользователь - может использовать систему
	UserStatus_ACTIVE UserStatus = 1
	// Заблокирован администратором (например, за нарушение правил)
	UserStatus_BLOCKED UserStatus = 2
	// Ожидает подтверждения email (после регистрации)
	UserStatus_PENDING_ACTIVATION UserStatus = 3
	// Удалён (soft delete - может быть восстановлен)
	UserStatus_DELETED UserStatus = 4
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "BLOCKED",
		3: "PENDING_ACTIVATION",
		4: "DELETED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"ACTIVE":                  1,
		"BLOCKED":                 2,
		"PENDING_ACTIVATION":      3,
		"DELETED":                 4,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_service_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_user_service_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{0}
}

// GetUserRequest - запрос на получение пользователя
// Ресурсы идентифицируются по имени в формате "user/{id}"
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя ресурса пользователя в формате "user/{id}"
	// Examples: "user/123", "user/abc-123-def"
	// Required: must start with "user/"
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// CreateUserRequest - запрос на создание пользователя
// ID может быть передан клиентом или генерируется сервером
type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор пользователя в формате "user/{id}"
	// Examples: "user/123", "user/abc-123-def"
	// Если не указан, генерируется сервером
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Email пользователя (обязательный для создания)
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Возраст пользователя в годах
	// Valid range: 0-150 (по статистике, живут не дольше ~122 лет)
	Age int32 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	// Дополнительные метаданные в формате key-value
	// Полезно для хранения кастомных данных без изменения схемы
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateUserRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// User - сущность пользователя
// Следует Google Cloud API Design Guidelines
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор пользователя в формате "user/{id}"
	// Output only - генерируется сервером
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Email пользователя (должен быть уникален)
	// Required: для аутентификации
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// Возраст пользователя в годах
	// Valid range: 0-150 (согласно statistics, живут не дольше ~122 лет)
	Age int32 `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	// Статус пользователя
	Status UserStatus `protobuf:"varint,6,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty"`
	// Дата создания записи
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Дата последнего обновления
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Дата последнего входа
	LastLoginAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	// Дополнительные метаданные в формате key-value
	// Полезно для хранения кастомных данных без изменения схемы
	Metadata      map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *User) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ErrorInfo - детали ошибки для использования в response
// Следует AIP-193: https://google.aip.dev/193
type ErrorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Причина ошибки
	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	// Домен, в котором произошла ошибка
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// Дополнительные детали
	Metadata      []string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ErrorInfo) GetMetadata() []string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_user_service_proto protoreflect.FileDescriptor

const file_user_service_proto_rawDesc = "" +
	"\n" +
	"\x12user_service.proto\x12\x04user\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"T\n" +
	"\x0eGetUserRequest\x12B\n" +
	"\auser_id\x18\x01 \x01(\tB)\x92A\x1b2\x19Unique identifier of user\xe0A\x02\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"\xa9\x03\n" +
	"\x11CreateUserRequest\x12U\n" +
	"\x04name\x18\x01 \x01(\tBA\x92A\x1d2\x1bUser ID in format user/{id}\xfaB\x1er\x1c\x10\x06\x18\x80\x012\x15^user/[a-zA-Z0-9_-]+$R\x04name\x127\n" +
	"\x05email\x18\x02 \x01(\tB!\x92A\x142\x12User email address\xe0A\x02\xfaB\x04r\x02`\x01R\x05email\x123\n" +
	"\x03age\x18\x03 \x01(\x05B!\x92A\x132\x11User age in years\xe0A\x01\xfaB\x05\x1a\x03\x18\x96\x01R\x03age\x12\x91\x01\n" +
	"\bmetadata\x18\x04 \x03(\v2%.user.CreateUserRequest.MetadataEntryBN\x92A(2&Additional metadata as key-value pairs\xfaB \x9a\x01\x1d\"\x14r\x122\x10^[a-zA-Z0-9_-]+$*\x05r\x03\x18\x80\bR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x04\n" +
	"\x04User\x127\n" +
	"\x04name\x18\x01 \x01(\tB#\xe0A\x03\xfaA\x1d\n" +
	"\x1bexample.googleapis.com/UserR\x04name\x12 \n" +
	"\x05email\x18\x04 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02`\x01R\x05email\x12\x1d\n" +
	"\x03age\x18\x05 \x01(\x05B\v\xe0A\x01\xfaB\x05\x1a\x03\x18\x96\x01R\x03age\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x10.user.UserStatusB\x03\xe0A\x03R\x06status\x12>\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAt\x12C\n" +
	"\rlast_login_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\vlastLoginAt\x12Y\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\x18.user.User.MetadataEntryB#\xfaB \x9a\x01\x1d\"\x14r\x122\x10^[a-zA-Z0-9_-]+$*\x05r\x03\x18\x80\bR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\tErrorInfo\x12!\n" +
	"\x06reason\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x06reason\x12!\n" +
	"\x06domain\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x06domain\x12+\n" +
	"\bmetadata\x18\x03 \x03(\tB\x0f\xfaB\f\x92\x01\t\x10\n" +
	"\"\x05r\x03\x18\x80\x02R\bmetadata*g\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\v\n" +
	"\aBLOCKED\x10\x02\x12\x16\n" +
	"\x12PENDING_ACTIVATION\x10\x03\x12\v\n" +
	"\aDELETED\x10\x042\xca\x01\n" +
	"\vUserService\x12U\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\n" +
	".user.User\"(\xdaA\auser_id\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/user/{user_id}\x12d\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\n" +
	".user.User\"1\xdaA\x17name,email,age,metadata\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/userBBZ@github.com/engineering-mastery/protobuf/examples/golang/api;userb\x06proto3"

var (
	file_user_service_proto_rawDescOnce sync.Once
	file_user_service_proto_rawDescData []byte
)

func file_user_service_proto_rawDescGZIP() []byte {
	file_user_service_proto_rawDescOnce.Do(func() {
		file_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)))
	})
	return file_user_service_proto_rawDescData
}

var file_user_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_service_proto_goTypes = []any{
	(UserStatus)(0),               // 0: user.UserStatus
	(*GetUserRequest)(nil),        // 1: user.GetUserRequest
	(*CreateUserRequest)(nil),     // 2: user.CreateUserRequest
	(*User)(nil),                  // 3: user.User
	(*ErrorInfo)(nil),             // 4: user.ErrorInfo
	nil,                           // 5: user.CreateUserRequest.MetadataEntry
	nil,                           // 6: user.User.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_user_service_proto_depIdxs = []int32{
	5, // 0: user.CreateUserRequest.metadata:type_name -> user.CreateUserRequest.MetadataEntry
	0, // 1: user.User.status:type_name -> user.UserStatus
	7, // 2: user.User.created_at:type_name -> google.protobuf.Timestamp
	7, // 3: user.User.updated_at:type_name -> google.protobuf.Timestamp
	7, // 4: user.User.last_login_at:type_name -> google.protobuf.Timestamp
	6, // 5: user.User.metadata:type_name -> user.User.MetadataEntry
	1, // 6: user.UserService.GetUser:input_type -> user.GetUserRequest
	2, // 7: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	3, // 8: user.UserService.GetUser:output_type -> user.User
	3, // 9: user.UserService.CreateUser:output_type -> user.User
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_user_service_proto_init() }
func file_user_service_proto_init() {
	if File_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_depIdxs,
		EnumInfos:         file_user_service_proto_enumTypes,
		MessageInfos:      file_user_service_proto_msgTypes,
	}.Build()
	File_user_service_proto = out.File
	file_user_service_proto_goTypes = nil
	file_user_service_proto_depIdxs = nil
}
