apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-app.fullname" . }}-config
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.app.name }}
  LOG_LEVEL: {{ .Values.app.logLevel }}
