syntax = "proto3";

package user;

import "google/api/annotations.proto";

option go_package = "github.com/engineering-mastery/protobuf/examples/go/pkg;user";

// UserService - сервис для управления пользователями
service UserService {
  // GetUser - получение данных о пользователе по его ID
  rpc GetUser(GetUserRequest) returns (User) {
    option (google.api.http) = {
      get: "/api/v1/users/{id}"
    };
  }
}

// GetUserRequest - запрос на получение пользователя
message GetUserRequest {
  // ID пользователя
  string id = 1;
}

// User - сущность пользователя
message User {
  // Уникальный идентификатор пользователя
  string id = 1;

  // Имя пользователя
  string name = 2;

  // Email пользователя
  string email = 3;

  // Возраст пользователя
  int32 age = 4;
}
